### ISSUE TITLE
Question about creating mesoracial ancestry categories

### ISSUE THREAD

**Issue by matthew-guerra** [matthew-guerra/master-project#1]
I was creating the European category and I saw in your recoding process on your project you included Australians and New Zealanders as European. Should I do the same with Tasmania? And where should I put people who put Australian Aborigines for ancestry? [Ancestry1 code (800-803)].

Thank you!

@AaronGullickson

**Comment by AaronGullickson** [comment]
@matthew-guerra Good questions. In practice, the Tasmanian and Aboriginal responses have not been used since Census 2000. You can check the number of actual responses in each category [here](https://usa.ipums.org/usa-action/variables/ANCESTR1#codes_section). You can switch to actual case counts at the top but anything with a "." is a non-existent category in that year. So, in practice, you don't need to try to code every single category.

Your question does hit on a deeper issue though - We are assuming Australians and New Zealanders are white, but that is not going to be true in all cases. This is actually true of all the ancestries here (e.g. some people who report an English ancestry will be black), so there will be some errors. But we are trying to code things in a way that minimizes those errors. In some cases, when an ancestry is very unclear, we should just drop those cases (IIRC, I did this with South African).

**Comment by matthew-guerra** [comment]
Forgot to reply but thank you!
